export const API_OPERATIONS = [
  ["get", "/health", "getHealth"],
  ["get", "/ready", "getReadiness"],
  ["get", "/v1/activity", "getServiceActivity"],
  ["get", "/metrics", "getMetrics"],
  ["get", "/openapi.json", "getOpenApi"],
  ["get", "/runtimes", "listRuntimes"],
  ["get", "/runtimes/{id}", "getRuntime"],
  ["get", "/state", "getState"],
  ["get", "/v1/inspection/runtimes", "listInspectionRuntimes"],
  ["get", "/v1/inspection/runtimes/{id}", "getInspectionRuntime"],
  ["get", "/v1/inspection/state", "getInspectionState"],
  ["get", "/v1/inspection/provider-instances", "listInspectionProviderInstances"],
  ["get", "/operations/{id}", "getLegacyOperation"],
  ["get", "/v1/operations/{id}", "getOperation"],
  ["get", "/v1/release-convergence", "getReleaseConvergence"],
  ["post", "/v1/allocations", "createAllocation"],
  ["get", "/v1/allocations/{id}", "getAllocation"],
  ["post", "/v1/allocations/{id}/renew", "renewAllocation"],
  ["post", "/v1/allocations/{id}/resolve", "resolveAllocation"],
  ["delete", "/v1/allocations/{id}", "releaseAllocation"],
  ["get", "/v1/context-status", "getContextStatus"],
  ["post", "/v1/contexts", "createContext"],
  ["get", "/v1/contexts", "listContexts"],
  ["delete", "/v1/contexts/{id}", "deleteContext"],
  ["post", "/v1/context-views", "createContextView"],
  ["get", "/v1/context-operations/{id}", "getContextOperation"],
  ["get", "/v1/personal-state/capability", "getPersonalStateCapability"],
  ["post", "/v1/context-sources", "provisionContextSource"],
  ["get", "/v1/context-source-operations/{incarnation}", "getContextSourceOperation"],
  ["post", "/v1/context-measurements", "createContextMeasurement"],
  ["get", "/v1/context-measurements/{id}", "getContextMeasurement"],
  ["post", "/v2/context-views", "createContextViewV2"],
  ["get", "/v2/context-views/{id}", "getContextViewV2"],
  ["get", "/v1/generation-attempts/{id}", "getGenerationAttempt"],
  ["post", "/v1/generation-attempts/{id}/cancel", "cancelGenerationAttempt"],
  ["post", "/v1/context-forget-operations", "createContextForgetOperation"],
  ["get", "/v1/context-forget-operations/{id}", "getContextForgetOperation"],
  ["get", "/v1/agent-profiles", "listAgentProfilesV1"],
  ["get", "/v2/agent-profiles", "listAgentProfiles"],
  ["get", "/v3/agent-profiles", "listAgentProfilesV3"],
  ["get", "/v1/services", "listServices"],
  ["get", "/v1/services/asr/health", "getAsrServiceHealth"],
  ["post", "/v1/agent-connections", "createAgentConnection"],
  ["get", "/v1/agent-connections/{id}", "getAgentConnection"],
  ["get", "/v1/agent-connections/{id}/health", "getAgentConnectionHealth"],
  ["get", "/v1/agent-connections/{id}/providers/{name}/health", "getAgentProviderHealth"],
  ["post", "/v1/agent-connections/{id}/claim", "claimAgentConnection"],
  ["post", "/v1/agent-connections/{id}/renew", "renewAgentConnection"],
  ["delete", "/v1/agent-connections/{id}", "releaseAgentConnection"],
  ["get", "/v1/models", "listOpenAiModels"],
  ["post", "/v1/chat/completions", "createChatCompletion"],
  ["post", "/v1/audio/transcriptions", "createTranscription"],
  ["post", "/v1/audio/speech", "createSpeech"],
  ["post", "/v1/embed", "createEmbedding"],
  ["post", "/v1/systemone", "createSystemOneDecision"],
  ["get", "/v1/music/providers", "listMusicProviders"],
  ["post", "/v1/music/generations", "createMusicGeneration"],
  ["get", "/v1/music/generations/{id}", "getMusicGeneration"],
  ["delete", "/v1/music/generations/{id}", "cancelMusicGeneration"],
  ["get", "/v1/music/generations/{id}/events", "getMusicGenerationEvents"],
  ["get", "/v1/music/generations/{id}/audio", "getMusicGenerationAudio"],
  ["get", "/v1/music/generations/{id}/metadata", "getMusicGenerationMetadata"],
  ["get", "/v1/music/favorites", "listMusicFavorites"],
  ["get", "/v1/music/favorites/{id}", "getMusicFavorite"],
  ["get", "/v1/music/favorites/{id}/audio", "getMusicFavoriteAudio"],
  ["get", "/v1/music/favorites/{id}/metadata", "getMusicFavoriteMetadata"],
  ["put", "/v1/music/generations/{id}/favorite", "favoriteMusicGeneration"],
  ["delete", "/v1/music/generations/{id}/favorite", "unfavoriteMusicGeneration"],
  ["get", "/v1/image-artifacts", "listImageArtifacts"],
  ["get", "/v1/image-artifacts/{id}", "getImageArtifact"],
  ["get", "/v1/image-artifacts/{id}/content", "getImageArtifactContent"],
  ["delete", "/v1/image-artifacts/{id}", "deleteImageArtifact"],
  ["get", "/v1/audio/voices", "listVoices"],
  ["get", "/v1/artifact-operations/{id}", "getArtifactOperation"],
  ["post", "/v1/artifacts/{id}/stage", "stageArtifact"],
  ["get", "/v1/runtime-releases", "listRuntimeReleases"],
  ["post", "/v1/runtime-releases/{id}/stage", "stageRuntimeRelease"],
  ["get", "/v1/deployments/{runtime}", "getRuntimeDeployment"],
  ["post", "/v1/deployments/{runtime}/plan", "planRuntimeDeployment"],
  ["post", "/v1/deployments/{runtime}/activate", "activateRuntimeDeployment"],
  ["post", "/v1/deployments/{runtime}/rollback", "rollbackRuntimeDeployment"],
  ["post", "/prepare", "prepareLegacyLease"],
  ["post", "/resolve", "resolveLegacyLease"],
  ["post", "/release", "releaseLegacyLease"],
] as const;

type ApiOperationId = typeof API_OPERATIONS[number][2];

export const SUCCESS_STATUSES_BY_OPERATION: Record<ApiOperationId, readonly string[]> = {
  getHealth: ["200"],
  getReadiness: ["200"],
  getServiceActivity: ["200"],
  getMetrics: ["200"],
  getOpenApi: ["200"],
  listRuntimes: ["200"],
  getRuntime: ["200"],
  getState: ["200"],
  listInspectionRuntimes: ["200"],
  getInspectionRuntime: ["200"],
  getInspectionState: ["200"],
  listInspectionProviderInstances: ["200"],
  getLegacyOperation: ["200"],
  getOperation: ["200"],
  getReleaseConvergence: ["200"],
  createAllocation: ["200", "202"],
  getAllocation: ["200"],
  renewAllocation: ["200"],
  resolveAllocation: ["200"],
  releaseAllocation: ["200"],
  getContextStatus: ["200"],
  createContext: ["200", "201"],
  listContexts: ["200"],
  deleteContext: ["204"],
  createContextView: ["200", "201"],
  getContextOperation: ["200"],
  getPersonalStateCapability: ["200"],
  provisionContextSource: ["200", "201"],
  getContextSourceOperation: ["200"],
  createContextMeasurement: ["200", "201"],
  getContextMeasurement: ["200"],
  createContextViewV2: ["200", "201"],
  getContextViewV2: ["200"],
  getGenerationAttempt: ["200"],
  cancelGenerationAttempt: ["200"],
  createContextForgetOperation: ["200", "202"],
  getContextForgetOperation: ["200"],
  listAgentProfilesV1: ["200"],
  listAgentProfiles: ["200"],
  listAgentProfilesV3: ["200"],
  listServices: ["200"],
  getAsrServiceHealth: ["200"],
  createAgentConnection: ["201", "202"],
  getAgentConnection: ["200"],
  getAgentConnectionHealth: ["200"],
  getAgentProviderHealth: ["200"],
  claimAgentConnection: ["200"],
  renewAgentConnection: ["200"],
  releaseAgentConnection: ["204"],
  listOpenAiModels: ["200"],
  createChatCompletion: ["200"],
  createTranscription: ["200"],
  createSpeech: ["200"],
  createEmbedding: ["200"],
  createSystemOneDecision: ["200"],
  listMusicProviders: ["200"],
  createMusicGeneration: ["202"],
  getMusicGeneration: ["200"],
  cancelMusicGeneration: ["200"],
  getMusicGenerationEvents: ["200"],
  getMusicGenerationAudio: ["200", "206"],
  getMusicGenerationMetadata: ["200"],
  listMusicFavorites: ["200"],
  getMusicFavorite: ["200"],
  getMusicFavoriteAudio: ["200", "206"],
  getMusicFavoriteMetadata: ["200"],
  favoriteMusicGeneration: ["200"],
  unfavoriteMusicGeneration: ["204"],
  listImageArtifacts: ["200"],
  getImageArtifact: ["200"],
  getImageArtifactContent: ["200"],
  deleteImageArtifact: ["200"],
  listVoices: ["200"],
  getArtifactOperation: ["200"],
  stageArtifact: ["202"],
  listRuntimeReleases: ["200"],
  stageRuntimeRelease: ["202"],
  getRuntimeDeployment: ["200"],
  planRuntimeDeployment: ["200"],
  activateRuntimeDeployment: ["202"],
  rollbackRuntimeDeployment: ["202"],
  prepareLegacyLease: ["200", "202"],
  resolveLegacyLease: ["200"],
  releaseLegacyLease: ["200"],
};

export const SUCCESS_SCHEMA_BY_OPERATION: Record<ApiOperationId, string> = {
  getHealth: "Health",
  getReadiness: "Readiness",
  getServiceActivity: "ServiceActivity",
  getMetrics: "Metrics",
  getOpenApi: "OpenApiDocument",
  listRuntimes: "RuntimeList",
  getRuntime: "Runtime",
  getState: "PublicClusterState",
  listInspectionRuntimes: "InspectionRuntimeList",
  getInspectionRuntime: "InspectionRuntime",
  getInspectionState: "InspectionClusterState",
  listInspectionProviderInstances: "InspectionProviderInstanceList",
  getLegacyOperation: "ControlOperation",
  getOperation: "ControlOperation",
  getReleaseConvergence: "ReleaseConvergenceStatus",
  createAllocation: "Allocation",
  getAllocation: "Allocation",
  renewAllocation: "Allocation",
  resolveAllocation: "AllocationResolveResponse",
  releaseAllocation: "Allocation",
  getContextStatus: "ContextStatus",
  createContext: "ContextDescriptor",
  listContexts: "ContextList",
  deleteContext: "ContextDescriptor",
  createContextView: "ContextView",
  getContextOperation: "ContextOperation",
  getPersonalStateCapability: "PersonalStateCapability",
  provisionContextSource: "SourceProvisionReceipt",
  getContextSourceOperation: "SourceProvisionReceipt",
  createContextMeasurement: "CanonicalMeasurementReceipt",
  getContextMeasurement: "CanonicalMeasurementReceipt",
  createContextViewV2: "ContextView",
  getContextViewV2: "PersonalStateViewReceipt",
  getGenerationAttempt: "GenerationAttempt",
  cancelGenerationAttempt: "GenerationAttempt",
  createContextForgetOperation: "ForgetOperation",
  getContextForgetOperation: "ForgetOperation",
  listAgentProfilesV1: "AgentProfileListV1",
  listAgentProfiles: "AgentProfileList",
  listAgentProfilesV3: "AgentProfileListV3",
  listServices: "ServiceHarness",
  getAsrServiceHealth: "AsrServiceHealth",
  createAgentConnection: "AgentConnection",
  getAgentConnection: "AgentConnection",
  getAgentConnectionHealth: "AgentConnectionHealth",
  getAgentProviderHealth: "AgentProviderHealth",
  claimAgentConnection: "AgentConnectionClaim",
  renewAgentConnection: "AgentConnection",
  releaseAgentConnection: "AgentConnection",
  listOpenAiModels: "OpenAiModelList",
  createChatCompletion: "UpstreamJson",
  createTranscription: "UpstreamJson",
  createSpeech: "Binary",
  createEmbedding: "EmbeddingResponse",
  createSystemOneDecision: "SystemOneResponse",
  listMusicProviders: "MusicProviderList",
  createMusicGeneration: "MusicGenerationJob",
  getMusicGeneration: "MusicGenerationJob",
  cancelMusicGeneration: "MusicGenerationJob",
  getMusicGenerationEvents: "ServerSentEvents",
  getMusicGenerationAudio: "Binary",
  getMusicGenerationMetadata: "MusicArtifactMetadata",
  listMusicFavorites: "MusicFavoriteList",
  getMusicFavorite: "MusicFavorite",
  getMusicFavoriteAudio: "Binary",
  getMusicFavoriteMetadata: "MusicArtifactMetadata",
  favoriteMusicGeneration: "MusicFavorite",
  unfavoriteMusicGeneration: "MusicFavorite",
  listImageArtifacts: "ImageArtifactList",
  getImageArtifact: "ImageArtifact",
  getImageArtifactContent: "Binary",
  deleteImageArtifact: "ImageArtifactDelete",
  listVoices: "AudioVoiceDiscovery",
  getArtifactOperation: "ArtifactOperation",
  stageArtifact: "ArtifactOperation",
  listRuntimeReleases: "RuntimeReleaseList",
  stageRuntimeRelease: "ArtifactOperation",
  getRuntimeDeployment: "RuntimeDeployment",
  planRuntimeDeployment: "RuntimeDeploymentPlan",
  activateRuntimeDeployment: "ArtifactOperation",
  rollbackRuntimeDeployment: "ArtifactOperation",
  prepareLegacyLease: "LegacyPrepareResponse",
  resolveLegacyLease: "LegacyResolveResponse",
  releaseLegacyLease: "LegacyReleaseResponse",
};
