import type { LocalServiceManager } from "./local-service-manager";
import type { LocalServicePrincipal } from "./routes/local-services";
import type { AgentConnectionCatalog, ClusterState, Registry } from "@larm/core";
import type { ControlEvent, ControlPlane } from "./controller";
import type { ArtifactManager } from "./artifact-manager";
import type { MetricsRegistry, RequestTracker } from "./metrics";
import type { DaemonIdentity } from "./identity";
import type { FetchLike } from "./gateway";
import type { RuntimeReleaseManager } from "./runtime-release-manager";
import type { ExecutionGate } from "./execution-gate";
import type { InferenceAuditRecorder } from "./inference-audit";
import type { AgentConnectionController } from "./agent-connection-controller";
import type { ModelBroker } from "./model-broker";
import type { ContextController } from "./context-controller";
import type { PersonalStateController } from "./personal-state-controller";
import type { GatewayReadiness } from "./gateway-lifecycle";
import type { MusicGenerationManager } from "./music-manager";
import type { ImageArtifactManager } from "./image-artifact-manager";
import type { ImageGenerationProvider } from "./image-generation-provider";

export type AppDeps = {
  localServiceManager?: LocalServiceManager;
  localServicePrincipals?: LocalServicePrincipal[];
  registry: Registry;
  getState: () => ClusterState;
  control: ControlPlane;
  apiToken?: string;
  allowAnonymousAgentConnections?: boolean;
  serviceHarnessAuthEnabled?: boolean;
  managementToken?: string;
  artifactManager?: ArtifactManager;
  runtimeReleaseManager?: RuntimeReleaseManager;
  metrics?: MetricsRegistry;
  requestTracker?: RequestTracker;
  gatewayFetch?: FetchLike;
  controlMaxBodyBytes?: number;
  gatewayMaxBodyBytes?: number;
  embeddingMaxBodyBytes?: number;
  gatewayTimeoutMs?: number;
  speechMaxBodyBytes?: number;
  stateMaxAgeMs?: number;
  now?: () => number;
  random?: () => string;
  onEvent?: (event: ControlEvent) => void;
  identity?: DaemonIdentity;
  getConfigRevision?: () => string;
  getReleaseConvergenceStatus?: () => Promise<unknown> | unknown;
  executionGate?: ExecutionGate;
  idempotencyTtlMs?: number;
  idempotencyLimit?: number;
  agentConnectionCatalog?: AgentConnectionCatalog;
  connectionSigningKey?: Uint8Array;
  connectionReadyTimeoutMs?: number;
  providerProbeTimeoutMs?: number;
  connectionPollIntervalMs?: number;
  connectionHistoryLimit?: number;
  inferenceAuditMode?: "off" | "metadata" | "full-required";
  inferenceAuditRecorder?: InferenceAuditRecorder;
  agentConnectionController?: AgentConnectionController;
  modelBroker?: ModelBroker;
  contextController?: ContextController;
  personalStateController?: PersonalStateController;
  personalStateMaxSourceBytes?: number;
  getGatewayReadiness?: () => GatewayReadiness;
  startupProbeToken?: string;
  musicManager?: MusicGenerationManager;
  imageArtifactManager?: ImageArtifactManager;
  imageGenerationProvider?: ImageGenerationProvider;
};
